insert overwrite table stock.t_ods_stock_basic partition (dt = "${dt}")
select input_time,
       ts_code,
       trade_date,
       name,
       pct_change,
       `close`,
       `change`,
       `open`,
       high,
       low,
       pre_close,
       vol_ratio,
       turn_over,
       swing,
       vol,
       amount,
       selling,
       buying,
       total_share,
       float_share,
       pe,
       industry,
       area,
       float_mv,
       total_mv,
       avg_price,
       strength,
       activity,
       avg_turnover,
       attack,
       interval_3,
       interval_6
from stock.t_ext_stock_basic
where dt = "${dt}"